var str="In space no one can hear your code";
str.split();
console.log(str.split());
console.log(str.split('e'));
console.log(str.split(' '));
console.log(str.split(''));
var arr=['B','n','n',5];
console.log(arr.join());
console.log(arr.join('a'));
console.log(arr.join(' '));
console.log(arr.join(''));
console.log(cargoHold.split(',').sort(),join(','));
console.log(holdcontents.toUpperCase());
console.log(holdcontents.split(','));
holdcontents=holdcontents.split(',');
console.log(holdcontents.join());