 var element1=["hydrogen",'H',1.008];
 var element2=["helium","He",4.003];
 var element26=["iron","Fe",55.85];
 table=[];
 table.push(element1);
 table.push(element2);
 table.push(element26);
 console.log(table);
 console.log(table[1]);
 console.log(table[1][1]);
 console.log(table[0][2]);
 console.log(table[1][0]);
 console.log(table[2][1]);
